title: Boise Math Circles
author: Joe Champion, Samuel Coskey, Margaret Kinzel, Zach Teitler
email: scoskey@boisestate.edu
description: >-
  Experience creative mathematics
url: "http://boisemathcircles.org"
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
math_engine: mathjax

permalink: /:categories/:title
header_pages: none

defaults: 
  - scope: 
      path: "bmc-sessions"
    values:
      layout: header-post
  - scope: 
      path: "bmtc-sessions"
    values:
      layout: header-post
